### ISSUE TITLE
 Cannot use import statement outside a module  "Mode SSR"

### ISSUE THREAD

**Issue by VictorFer25** [17axah/vue-router-auth#1]
In node_modules/vue-router-auth/index.js:1
import Vue from 'vue'; <-----------------------

Any solution?

**Comment by 17axah** [comment]
It is necessary to add transpile. If you are using nuxt, you can write in nuxt.config.js:
```javascript
export default {
    ...
    build: {
        transpile: ['vue-router-auth']
    }
}
```

**Comment by VictorFer25** [comment]
I am using quasar, in my quasar.conf.js file I have the following configured and it does not work
build: {
      vueRouterMode: 'history', // available values: 'hash', 'history'
      transpile:true,
      transpileDependencies: ['vue-router-auth'],
}

**Comment by 17axah** [comment]
Should work. At least it works for me with:
```javascript
build: {
      vueRouterMode: 'history',
      transpile: true,
      transpileDependencies: ['vue-router-auth'],
    },
```

If you import the module like this:
```javascript
import VueRouterAuth from 'vue-router-auth/index.js'
```

Import like this
```javascript
import VueRouterAuth from 'vue-router-auth'
```

**Comment by VictorFer25** [comment]
Thank you very much, it worked, there is only one problem with the other library but it is easy to solve
